version: "3"

services:
  dev:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/opt/project
    working_dir: /opt/project
    command: tail -f /dev/null
    ports:
      - 4000:4000